SELECT D_NEXT_O_ID FROM district \
	WHERE D_W_ID = 1 AND D_ID = 1;
SELECT COUNT(DISTINCT (S_I_ID)) AS STOCK_COUNT FROM order_line, stock \
	WHERE OL_W_ID = 1 AND OL_D_ID = 1 AND OL_O_ID < 10 AND OL_O_ID >= 4 AND S_W_ID = 1 AND S_I_ID = OL_I_ID AND S_QUANTITY < 20.0;