FROM tgagor/centos:stream8

ENV container docker
RUN yum -y update; yum clean all
RUN yum -y install systemd; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN yum install -y bzip2 bzip2-devel curl libaio wget tree net-tools
RUN yum -y install java-1.8.0-openjdk-devel
RUN yum -y groupinstall "Development Tools"
RUN yum -y install docker cmake clang openssl openssl-devel llvm llvm-devel llvm-libs redhat-lsb-core
RUN yum -y install glibc-langpack-en
RUN yum -y install gcc-toolset-9-libatomic-devel
RUN yum -y install libaio-devel ncurses-devel pam-devel libffi-devel python3 python3-devel libnsl boost-devel vim
RUN alternatives --set python /usr/bin/python3

#RUN cd /tmp && git clone https://github.com/opengauss-mirror/openGauss-third_party.git
#RUN cd /tmp && wget https://opengauss.obs.cn-south-1.myhuaweicloud.com/1.1.0/x86/openGauss-1.1.0-CentOS-64bit-all.tar.gz
RUN cd /tmp && \
    wget https://opengauss.obs.cn-south-1.myhuaweicloud.com/2.1.0/openGauss-third_party_binarylibs.tar.gz && \
    tar zxvf openGauss-third_party_binarylibs.tar.gz && rm -f openGauss-third_party_binarylibs.tar.gz
RUN cd /tmp/openGauss-third_party_binarylibs/buildtools/centos7.6_x86_64/ && \
    ln -s gcc7.3 gcc8.5
RUN rm -rf /tmp/openGauss-third_party_binarylibs/dependency/centos7.6_x86_64/boost
RUN mkdir -p /usr/lib64/huawei && \
    echo '/usr/lib64/huawei' > /etc/ld.so.conf.d/huawei-x86_64.conf && \
    cp /tmp/openGauss-third_party_binarylibs/platform/centos7.6_x86_64/Huawei_Secure_C/Dynamic_Lib/libsecurec.so /usr/lib64/huawei/
RUN cd /tmp && \
   git clone --recursive https://github.com/dmlc/xgboost && \
   cd xgboost && \
   mkdir build && \
   cd build && \
   cmake .. && \
   make -j 4 && \
   make install && \
   cd /tmp && \
   rm -rf /tmp/xgboost && \
   cd
RUN cd /tmp && \
   git clone https://github.com/fmtlib/fmt.git && \
   cd fmt && \
   git checkout 7.1.3 && \
   mkdir build && \
   cd build && \
   cmake -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0' -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && \
   make -j 4 && \
   make install && \
   cd /tmp && \
   rm -rf /tmp/fmt && \
   cd
RUN groupadd dbgrp && \
    useradd omm && \
    usermod -G dbgrp omm && \
    echo "Test3456" | passwd --stdin omm
RUN su - omm -c 'echo "export GAUSSHOME=/opt/opengauss" >> .bashrc' && \
    su - omm -c 'echo "export PATH=$GAUSSHOME/bin:$PATH" >> .bashrc' && \
    su - omm -c 'echo "export LD_LIBRARY_PATH=$GAUSSHOME/lib:$LD_LIBRARY_PATH" >> .bashrc' && \
    su - omm -c 'echo "export GS_CLUSTER_NAME=dbCluster" >> .bashrc' && \
    su - omm -c 'echo "export GAUSSLOG=/opt/opengauss/logs" >> .bashrc' && \
    su - omm -c 'echo "export PGDATA=/opt/opengauss/data" >> .bashrc'

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/bin/bash"]
